server:
  port: 8808

logging:
  file:
#    在项目根目录下生成目录
    path: log

swagger:
  #swagger是否开启
  swagger-ui-open: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0

mybatis-plus:
  configuration:
#    开启驼峰命名对应字段
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
#   打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml

token:
#  超时时间(毫秒)
  time_out: 600000

#多线程线程池
executor:
  # 配置核心线程数
  corePoolSize: 5
  # 配置最大线程数
  maxPoolSize: 10
  # 配置队列大小
  queueCapacity: 100
  # 配置线程池中的线程的名称前缀
  threadNamePrefix: async-service-